---
- hosts: "{{ host }}"
  remote_user: root
  become: yes

  pre_tasks:
    - name: Switch http -> https in ubuntu.sources
      replace:
        path: /etc/apt/sources.list.d/ubuntu.sources
        regexp: 'http://'
        replace: 'https://'

    - name: Update apt cache
      apt:
        update_cache: yes

  tasks:
    - name: Remove automatic updates
      apt:
        name: unattended-upgrades
        state: absent

    - name: Base dependencies
      apt:
        pkg:
          - nmap
          - ncat
          - python3
          - python3-pip
          - net-tools
          - unzip
        state: present
        update_cache: yes
