---
- hosts: "{{ host }}"
  tasks:
    - name: Check if SSH private key exists
      become: true
      become_user: "{{ host_user }}"
      stat:
        path: "~/.ssh/id_ed25519"
      register: ssh_key_check

    - name: Create SSH directory if it does not exist
      become: true
      become_user: "{{ host_user }}"
      file:
        path: "~/.ssh"
        state: directory
        mode: "0700"
      when: not ssh_key_check.stat.exists

    - name: Generate SSH key if it does not exist
      become: true
      become_user: "{{ host_user }}"
      shell:
        cmd: ssh-keygen -t ed25519 -f '.ssh/id_ed25519' -q -N ""
        creates: "~/.ssh/id_ed25519"
        chdir: "~"
      when: not ssh_key_check.stat.exists

    - name: Ensure correct permissions for SSH key
      become: true
      become_user: "{{ host_user }}"
      file:
        path: ~/.ssh/id_ed25519
        mode: '0600'
      when: ssh_key_check.stat.exists

    - name: Read SSH key
      become: true
      become_user: "{{ host_user }}"
      ansible.builtin.slurp:
        src: "~/.ssh/id_ed25519.pub"
      register: leader_ssh_key

    - name: Save the public key for use
      set_fact:
        public_key: "{{ leader_ssh_key['content'] | b64decode }}"

    - name: add to ssh config
      become: true
      become_user: "{{ host_user }}"
      blockinfile:
        state: present
        insertafter: EOF
        dest: "~/.ssh/config"
        content: |
          Host {{ follower_user }}
            HostName {{ hostvars[follower]['ansible_host'] }}
            User {{ follower_user }}
            IdentityFile ~/.ssh/id_ed25519
        create: true
        mode: "0600"
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ follower_user }}"

- hosts: "{{ follower }}"
  tasks:
    - name: Add public SSH key to authorized keys
      authorized_key:
        user: "{{ follower_user }}"
        key: "{{ hostvars[host]['public_key'] }}"

- hosts: "{{ follower }}"
  tasks:
    - name: Print actual hostname and IP
      command: hostname -I
      register: actual_ip
    - name: Show actual IP
      debug:
        msg: "Connected to IP: {{ actual_ip.stdout }}"
    - name: Add public SSH key to authorized keys
      authorized_key:
        user: "{{ follower_user }}"
        key: "{{ hostvars[host]['public_key'] }}"
