install_base_packages: src/playbooks/plays/install_base_packages.yml
kali_packages: src/playbooks/plays/kali_packages.yml
check_if_host_up: src/playbooks/plays/check_if_host_up.yml
setup_ssh_keys: src/playbooks/plays/setup_ssh_keys.yml
create_ssh_key: src/playbooks/plays/create_ssh_key.yml
add_to_ssh_config: src/playbooks/plays/add_to_ssh_config.yml
reset_ssh_config: src/playbooks/plays/reset_ssh_config.yml
wait_for_port: src/playbooks/plays/wait_for_port.yml
install_falco_nostart: src/playbooks/plays/install_falco_nostart.yml
install_falco: src/playbooks/plays/install_falco.yml
install_sysflow_nostart: src/playbooks/plays/install_sysflow_nostart.yml
install_sysflow: src/playbooks/plays/install_sysflow.yml
start_sysflow: src/playbooks/plays/start_sysflow.yml
deploy_honey_service: src/playbooks/plays/deploy_honey_service.yml
deploy_honey_ssh: src/playbooks/plays/deploy_honey_ssh.yml
setup_fake_credential: src/playbooks/plays/setup_fake_credential.yml
start_defender_services: src/playbooks/plays/start_defender_services.yml
bake_attacker: src/playbooks/plays/bake_attacker.yml
install_caldera_attacker: src/playbooks/plays/install_caldera_attacker.yml
install_caldera_defender: src/playbooks/plays/install_caldera_defender.yml
start_attacker: src/playbooks/plays/start_attacker.yml
ftp_access: src/playbooks/plays/ftp_access.yml
nostromo_rce: src/playbooks/plays/nostromo_rce.yml
sudobaron: src/playbooks/plays/sudobaron.yml
sudobypass: src/playbooks/plays/sudobypass.yml
sudoedit: src/playbooks/plays/sudoedit.yml
writeable_passwd: src/playbooks/plays/writeable_passwd.yml
writeable_sudoers: src/playbooks/plays/writeable_sudoers.yml
ssh_enable_password_login: src/playbooks/plays/ssh_enable_password_login.yml
equifax_ssh_config: src/playbooks/plays/equifax_ssh_config.yml
vsftpd_backdoor: src/playbooks/plays/vsftpd_backdoor.yml
vsftpd_backdoor_run: src/playbooks/plays/vsftpd_backdoor_run.yml
weak_user_password: src/playbooks/plays/weak_user_password.yml
netcat_shell: src/playbooks/plays/netcat_shell.yml
rsync: src/playbooks/plays/rsync.yml
chkrootkit: src/playbooks/plays/chkrootkit.yml
setup_struts: src/playbooks/plays/setup_struts.yml
add_flag: src/playbooks/plays/add_flag.yml
add_data: src/playbooks/plays/add_data.yml
join_ad: src/playbooks/plays/join_ad.yml
samba_ad: src/playbooks/plays/samba_ad.yml
add_ad_users: src/playbooks/plays/add_ad_users.yml
add_ad_groups: src/playbooks/plays/add_ad_groups.yml
install_package: src/playbooks/plays/install_package.yml
create_user: src/playbooks/plays/create_user.yml
service_action: src/playbooks/plays/service_action.yml
reboot: src/playbooks/plays/reboot.yml
cron_job: src/playbooks/plays/cron_job.yml
file_remote_copy: src/playbooks/plays/file_remote_copy.yml
git_clone: src/playbooks/plays/git_clone.yml
run_command: src/playbooks/plays/run_command.yml
add_ssh_key: src/playbooks/plays/add_ssh_key.yml
allow_traffic: src/playbooks/plays/allow_traffic.yml
create_directory: src/playbooks/plays/create_directory.yml
change_password: src/playbooks/plays/change_password.yml
bake_ubuntu_base: src/playbooks/plays/bake_ubuntu_base.yml
bake_webserver: src/playbooks/plays/bake_webserver.yml
bake_attacker_image: src/playbooks/plays/bake_attacker_image.yml
bake_database: src/playbooks/plays/bake_database.yml
bake_employee: src/playbooks/plays/bake_employee.yml
bake_manage_host: src/playbooks/plays/bake_manage_host.yml
enable_root_ssh: src/playbooks/plays/enable_root_ssh.yml
